### ISSUE TITLE
Add section on the build system

### ISSUE THREAD

**Issue by jarolrod** [chaincodelabs/onboarding-to-bitcoin-core#27]
The build system is an integral part of bitcoin core. Priorities for the build system and what dependencies we want bitcoin core to use have historically led to heavy refactoring of the code. The philosophy behind the build system also touches on ideas of development behind bitcoin core is to be treated as is security oriented software. It is also how we get reproducible binaries which is pretty important to talk about.

Looking for concept ack as it could be deemed info on the build system is not necessary for onboarding. Happy to take this on and open a PR if consensus.

**Comment by Hasancan2** [comment]
Lütfen Ne gerekiyorsa yap

9 May 2022 Pzt 13:00 tarihinde Jarol Rodriguez ***@***.***>
şunu yazdı:

**Comment by adamjonas** [comment]
Let's add the section and maybe some kind soul will help us write it.

**Comment by willcl-ark** [comment]
Empty section added in https://github.com/chaincodelabs/onboarding-to-bitcoin-core/commit/45584fe114736f86742fa1a59e83ebb428c10594
