### ISSUE TITLE
Extract from 01 and 02 into a Development Process Section 

### ISSUE THREAD

**Issue by jarolrod** [chaincodelabs/onboarding-to-bitcoin-core#32]
You could move sections like:
- `Decentralized Dev`
- `Bitcoin Core Dev Process and Doc`
- `Reviews`
- `Commit Messages`
- `Continuous Integration`
- `Getting Started with Development`

Into a new `02_development-process.adoc`, and the remaining material in the current `02` renamed to `03`, update number accordingly. Exercises in `01` that are related to the development process can be moved to this new section. 

After doing this, the `overview-and-architecture` section can now be focused on just that, and material within it expanded on.

**Comment by amovfx** [comment]
I agree with this. I think that Organizational structure and platforms the organization uses and the inherent risks, are enough of for the first chapter.

I think the life cycle can be moved to a different chapter to detail the roles and responsibilities.

**Comment by willcl-ark** [comment]
Thanks both. This has now been done in another branch (check https://obc.256k1.dev for latest unstable version)
