### ISSUE TITLE
Use per-chapter checkpoints over one global one?

### ISSUE THREAD

**Issue by MarcoFalke** [chaincodelabs/onboarding-to-bitcoin-core#34]
Currently the whole website is "checkpointed" at one commit ("This document was created from Bitcoin Core at commit [4b5659c6](https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e)").

This may be good enough for now, but as the website gets increasingly outdated, it may discourage people from updating it, since it requires the entirety to be updated. Maybe it would be better to "checkpoint" each chapter separately, so that (for example) wallet people can update "their" chapter while leaving other chapters untouched?

**Comment by willcl-ark** [comment]
Hey @MarcoFalke, thanks for the feedback.

I certainly agree on the general point that the material going out of date -- many instances I am already aware of! -- is something we should do more to avoid.

I was going to attempt to drop as many code snippets as possible in the next pass, and try to replace them with words describing the process (and where possible the rationale for taking such an approach), but I really appreciate the idea of checkpointing per chapter as I had not thought of this. It would indeed make those sections of code which remained easier to be updated chapter-by-chapter!

**Comment by willcl-ark** [comment]
I am going to close this as all sections (except script) have been given a pretty thorough re-work, now have per-chapter date markers (currently all set to v.23.0) and have had most of the code snippets removed to try and address individual out-of-date concerns.
