### ISSUE TITLE
Ch 01 clean build instructions didn't work on macos

### ISSUE THREAD

**Issue by amovfx** [chaincodelabs/onboarding-to-bitcoin-core#37]
Not sure if this is just a difference in OS.

I noticed ../.autogen.sh, on the latest pull, is just named ../autogen.sh for me on MacOs.
Same with the configure commands ../configure --regular options

**Comment by adamjonas** [comment]
linking https://github.com/chaincodelabs/onboarding-to-bitcoin-core/pull/38#issuecomment-1193135538 to here

**Comment by willcl-ark** [comment]
Fixed in #38
