### ISSUE TITLE
Mention `stress test` in `Tests overview`

### ISSUE THREAD

**Issue by brunoerg** [chaincodelabs/onboarding-to-bitcoin-core#42]
In [Tests overview](https://obc.256k1.dev/#_tests_overview), it would be great to short mention we have `stress test` in Core? It's into the functional test (to not rewrite same code) but we can consider it a different category of test. 

See: https://github.com/bitcoin/bitcoin/commit/d9803f7a0a33688f7429cf10384244f4770851ca

**Comment by willcl-ark** [comment]
Hello Bruno, thanks for the feedback.

I don't think I quite see how this test is different from many of the other `feature_*.py` tests? We have e.g. abortnode, dbcrash, shutdown etc. which all might be considered similar, perhaps you could explain a little further?

I think that personally if I heard that we had a "stress test" I would take it to mean that we have a test which exercised many of the potential DoS vectors to try and stress the CPU/RAM/Disk and check that the node doesn't fall over (although I fully take the point that the author of that PR named the commit " test: add stress tests for initialization ") 😄

**Comment by brunoerg** [comment]
Hey, sorry for the late reply! 

I think you're right, this specific test is not sooo different compared to other ones we have in `feature_*.py`, just thought interesting to short mention it because there were some new contributors I talked about it that didn't know we could have into our functional tests this kind of tests (e.g. stressing initialization by disturbing files, etc.).

**Comment by willcl-ark** [comment]
Hmmm, I agree with you actually!

Do you think something like [this commit](https://github.com/chaincodelabs/onboarding-to-bitcoin-core/commit/f7da6c6839a9efdb33741ba3665027a0139d9cd8) would cover it adequately enough? (and, if you'd prefer to submit the PR yourself, then please feel free!)

**Comment by brunoerg** [comment]
Yes, that commit sounds good.
