### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by adam2k** [chaincodelabs/onboarding-to-bitcoin-core#54]
## Problem:

This repo currently does not have any CI/CD.  It is a manual build and deploy process.  If the person(s) responsible for managing this repo are unavailable then no code changes can be deployed.

## Suggestion:

1. Enable GitHub pages for the `main/master` branch for this repo
2. Point the CNAME subdomain records to the Github location.  Read the [docs here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)
3. Setup Github Actions to run the build command `asciidoctor -r asciidoctor-diagram index.adoc`.  Something like this could be a good [starting point](https://github.com/marketplace/actions/build-asciidoctor-action)

### Alternate Suggestion:

If steps 1 and 2 are inappropriate then Github Actions could still be used to deploy the built `index.html` to the current hosting location, but will require some extra Github Actions and some access keys to be added to this repository secrets under the admin Settings page.

**Comment by adamjonas** [comment]
closed via [#60](https://github.com/chaincodelabs/onboarding-to-bitcoin-core/pull/60), fe2ed8c775903ab11a7ede07bd3910e51652e9fd and 6179061e7490b5e1073e3637668754932537612c
