### ISSUE TITLE
Multiwallet link is dead

### ISSUE THREAD

**Issue by hodlinator** [chaincodelabs/onboarding-to-bitcoin-core#82]
[multiwallet.adoc](https://github.com/chaincodelabs/onboarding-to-bitcoin-core/blob/9c85a3cf7a0bb75f011ca5ea33f82850ebfe90e9/multiwallet.adoc?plain=1) links to https://github.com/bitcoin/bitcoin/projects/2 which isn't recognized by GitHub (any longer?).

**Comment by adamjonas** [comment]
Thanks for flagging. I'll replace with the https://github.com/bitcoin/bitcoin/pull/8694 unless there is a better suggestion.

**Comment by hodlinator** [comment]
Fine by me!
