### ISSUE TITLE
Remove `libbitcoinconsensus`?

### ISSUE THREAD

**Issue by brunoerg** [chaincodelabs/onboarding-to-bitcoin-core#84]
`libbitcoinconsensus` has been removed from Bitcoin Core. Worth removing it here or mentioning the removal? There is a part of the doc that says _"The functionality is planned to be extended to e.g. UTXO management in upcoming releases, but the interface for existing methods should remain stable."_  which is not true anymore.

**Comment by adamjonas** [comment]
@brunoerg would you be up for suggesting the edit with a PR?

**Comment by brunoerg** [comment]
> @brunoerg would you be up for suggesting the edit with a PR?

Yes, will do it.

**Comment by willcl-ark** [comment]
Thanks Bruno. I've taken in #85
